#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Get PHP and Imagick versions.
#======================================================================================================================

cd /tmp

PHP_VERSION=$(cat PHP_BUILD)
bf-echo "PHP version ${PHP_VERSION}."

IMAGICK_VERSION=$(cat IMAGICK_BUILD)
bf-echo "Imagick version ${IMAGICK_VERSION}."

REDIS_VERSION=$(cat REDIS_BUILD)
bf-echo "Redis version ${REDIS_VERSION}."


#======================================================================================================================
# Install PHP and Imagick dependencies and packages.
#======================================================================================================================

bf-echo "Installing PHP v${PHP_VERSION}..."
chmod +x ./install-php && ./install-php ${PHP_VERSION}
bf-done

bf-echo "Installing Imagick v${IMAGICK_VERSION}..."
chmod +x ./install-php-imagick && ./install-php-imagick ${IMAGICK_VERSION}
bf-done

bf-echo "Installing Redis v${REDIS_VERSION}..."
chmod +x ./install-php-redis && ./install-php-redis ${REDIS_VERSION}
bf-done


#======================================================================================================================
# Run WordPress installation.
#======================================================================================================================

chmod +x /usr/bin/bf/wp-install
wp-install


#======================================================================================================================
# Create WordPress directory.
#======================================================================================================================

bf-echo "Creating WordPress content directory."
mkdir /wp-content


#======================================================================================================================
# Cleanup.
#======================================================================================================================

bf-echo "Removing /www files."
rm -f /www/*
