ARG PHP_VERSION=7.4.14-r0
FROM bcgdesign/nginx-php:auto

LABEL maintainer="Ben Green <ben@bcgdesign.com>" \
    org.label-schema.name="WordPress" \
    org.label-schema.version="latest" \
    org.label-schema.vendor="Ben Green" \
    org.label-schema.schema-version="1.0"

ARG PHP_VERSION
ARG IMAGICK_VERSION=3.4.4-r7

RUN apk -U upgrade \
    && apk add \
        curl \
        unzip \
        php7-cgi@edgecomm=${PHP_VERSION} \
        php7-ctype@edgecomm=${PHP_VERSION} \
        php7-curl@edgecomm=${PHP_VERSION} \
        php7-dom@edgecomm=${PHP_VERSION} \
        php7-exif@edgecomm=${PHP_VERSION} \
        php7-fileinfo@edgecomm=${PHP_VERSION} \
        php7-ftp@edgecomm=${PHP_VERSION} \
        php7-gd@edgecomm=${PHP_VERSION} \
        php7-gettext@edgecomm=${PHP_VERSION} \
        php7-iconv@edgecomm=${PHP_VERSION} \
        php7-imap@edgecomm=${PHP_VERSION} \
        php7-json@edgecomm=${PHP_VERSION} \
        php7-mbstring@edgecomm=${PHP_VERSION} \
        php7-mysqlnd@edgecomm=${PHP_VERSION} \
        php7-mysqli@edgecomm=${PHP_VERSION} \
        php7-sodium@edgecomm=${PHP_VERSION} \
        php7-openssl@edgecomm=${PHP_VERSION} \
        php7-simplexml@edgecomm=${PHP_VERSION} \
        php7-soap@edgecomm=${PHP_VERSION} \
        php7-sockets@edgecomm=${PHP_VERSION} \
        php7-xml@edgecomm=${PHP_VERSION} \
        php7-xmlrpc@edgecomm=${PHP_VERSION} \
        php7-xmlreader@edgecomm=${PHP_VERSION} \
        php7-zip@edgecomm=${PHP_VERSION} \
        php7-pecl-imagick@edgecomm=${IMAGICK_VERSION} \
    && rm -rf /var/cache/apk/* /www/* /tmp/*

ENV \
    # set to a valid WordPress locale or the installation will fail
    LOCALE="en_GB" \
    # set to 1 to wipe WordPress files and start again (WARNING: YOU WILL LOSE EVERYTHING!)
    CLEAN_INSTALL=0 \
    # set to 1 to generate wp-config.php based on environment variables
    GENERATE_CONFIG=0 \
    # database name
    WPDB_NAME= \
    # database user
    WPDB_USER= \
    # database password
    WPDB_PASS= \
    # database host
    WPDB_HOST= \
    # database character set
    WPDB_CHARSET="utf8mb4" \
    # database collation
    WPDB_COLLATE= \
    # database prefix
    WPDB_PREFIX="wp_" \
    # whether or not to enable debug mode
    DEBUG="false" \
    # whether or not to enable HTTPS behind a proxy server
    ENABLE_HTTPS_BEHIND_PROXY=true \
    # set to 1 to use system cron instead of WordPress cron (improves page performance)
    # you must add define('DISABLE_WP_CRON', true); to wp-config.php to make a difference
    USE_SYSTEM_CRON=0

COPY ./overlay /

VOLUME [ "/wp" ]
