#!/usr/bin/with-contenv bash

#======================================================================================================================
# Download WordPress
#======================================================================================================================

cd /tmp

URL="https://${WORDPRESS_LOCALE}.wordpress.org/wordpress-${WORDPRESS_VERSION}-${WORDPRESS_LOCALE}.zip"
echo " - downloading ${URL}..."
curl -sL -o wp.zip ${URL}
unzip -q wp.zip && rm wp.zip

if [ -d ./wordpress ] ; then
    echo " - done."
else
    echo " - error."
    exit 1
fi


#======================================================================================================================
# Move WordPress files to /www
#======================================================================================================================

echo " - moving WordPress files to /www..."
rm -rf /www/*
mv wordpress/* /www/ && rm -rf wordpress
echo " - done."
