#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

WP_SRC=${BF_SRC}/wordpress
bf-env "WP_SRC" "${WP_SRC}"
bf-env "NGINX_ROOT" "${WP_SRC}"
