#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If /www/public already exists, migration to v5 has been done.
#======================================================================================================================

PUBLIC=/www/public
if [ -d ${PUBLIC} ] ; then
    bf-echo "${PUBLIC} already exists."
    exit 0
fi


#======================================================================================================================
# If nothing exists in /www, simply create /www/public.
#======================================================================================================================

if [ "$(ls /www)" = "" ] ; then
    bf-echo "Creating ${PUBLIC}."
    mkdir ${PUBLIC}
    exit 0
fi


#======================================================================================================================
# Move /www files to a temporary directory, then to /www/public and reapply permissions.
#======================================================================================================================

bf-echo "Moving /www/* to ${PUBLIC}..."

bf-debug " .. create temporary directory..."
TMP_DIR=`mktemp -d -t nginx.XXXXXX`

bf-debug " .. moving /www/* to ${TMP_DIR}..."
mv /www/* ${TMP_DIR}/

bf-debug " .. moving ${TMP_DIR} to ${PUBLIC}..."
mv ${TMP_DIR} ${PUBLIC}

bf-debug " .. reapplying permissions"
bf-ch-apply "${BF_CH_D}/11-nginx-www"

bf-done
