#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "WP_LIB" "${BF_LIB}/wp"

bf-env "WP_CONFIG" "${WP_SRC}/wp-config.php"
bf-env "WP_FIREWALL" "${WP_SRC}/firewall.php"

WP_CONTENT="/wp-content"
bf-env "WP_CONTENT" "${WP_CONTENT}"
bf-env "WP_SALT" "${WP_CONTENT}/salt"

WP_CONTENT_SRC="${WP_SRC}${WP_CONTENT}"
bf-env "WP_CONTENT_SRC" "${WP_CONTENT_SRC}"
bf-env "WP_CONTENT_DEFAULT" "${WP_CONTENT_SRC}-default"

WP_LANGUAGES="${WP_CONTENT}/languages"
bf-env "WP_LANGUAGES" "${WP_LANGUAGES}"

WP_PLUGINS="${WP_CONTENT}/plugins"
bf-env "WP_PLUGINS" "${WP_PLUGINS}"
bf-env "WP_NINJAFIREWALL" "${WP_PLUGINS}/ninjafirewall/lib/firewall.php"

WP_THEMES="${WP_CONTENT}/themes"
bf-env "WP_THEMES" "${WP_THEMES}"

WP_UPLOADS="${WP_CONTENT}/uploads"
bf-env "WP_UPLOADS" "${WP_UPLOADS}"
