#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "WP_LIB" "${BF_LIB}/wp"

bf-env "WP_CONFIG" "${WP_SRC}/wp-config.php"
bf-env "WP_CONTENT" "/wp-content"
bf-env "WP_CONTENT_SRC" "${WP_SRC}/wp-content"
bf-env "WP_CONTENT_DEFAULT" "${BF_SRC}/wp-content-default"
bf-env "WP_WAF_FIREWALL" "${WP_CONTENT}/nfwlog/ninjafirewall.php"
