#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "WP_LIB" "${BF_LIB}/wp"

bf-env "WP_CONFIG" "${WP_SRC}/wp-config.php"

WP_CONTENT="/wp-content"
bf-env "WP_CONTENT" "${WP_CONTENT}"
bf-env "WP_CONTENT_SRC" "${WP_SRC}${WP_CONTENT}"
bf-env "WP_CONTENT_DEFAULT" "${BF_SRC}${WP_CONTENT}-default"
bf-env "WP_FIREWALL" "${WP_SRC}/firewall.php"
bf-env "WP_WAF_FIREWALL" "${WP_CONTENT}/nfwlog/ninjafirewall.php"
bf-env "WP_SALT" "${WP_CONTENT}/salt"
