#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Override configuration.
#======================================================================================================================

bf-echo "Overriding php.ini configuration values..."

declare -A VALUES
VALUES["cgi.fix_pathinfo"]="0"

source ${BF_INC}/php-replace-ini.sh
replace-ini VALUES ${PHP_DIR}/php.ini

bf-done
