#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If WP_CONFIG doesn't exist, the setup has gone wrong.
#======================================================================================================================

[[ ! -f ${WP_CONFIG} ]] && bf-error "${WP_CONFIG} does not exist."


#======================================================================================================================
# Run install NinjaFirewall executable, and activate full WAF mode
#======================================================================================================================

USER_INI=${WP_SRC}/.user.ini
FIREWALL=${WP_SRC}/firewall.php
rm -f ${USER_INI} ${FIREWALL}

if [ "${WP_INSTALL_NINJAFIREWALL-}" = "1" ] ; then

    ${WP_LIB}/install-ninjafirewall

    bf-debug "Generating files to support full WAF mode."

    bf-esh ${BF_TEMPLATES}/firewall.php.esh ${FIREWALL}
    bf-ch -o www:www ${FIREWALL}

    bf-esh ${BF_TEMPLATES}/user.ini.esh ${USER_INI}
    bf-ch -o www:www ${USER_INI}

fi

wp-setup-complete
