#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If WP_CONFIG doesn't exist, the setup has gone wrong.
#======================================================================================================================

[[ ! -f ${WP_CONFIG} ]] && bf-error "${WP_CONFIG} does not exist."


#======================================================================================================================
# Create link to wp-config.php.
# Arguments:
#   -f  Force - remove existing destination files
#   -s  Symbolic - create a symbolic link instead of hard link (required when using mounted volumes)
#======================================================================================================================

ln -fs ${WP_CONFIG} ${WP_CONFIG_SRC}
