#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If setup was not completed succesfully, terminate and close down the container.
#======================================================================================================================

if [ "${SETUP_COMPLETE-}" = "1" ] ; then
    bf-clear
    bf-ok "WordPress setup complete."
    exit 0
fi

bf-notok "WordPress setup did not complete successfully, terminating container."
bf-cont-terminate
