#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Download WordPress if the source is not part of the image.
#======================================================================================================================

WP_SRC=/tmp/wordpress
[[ ! -d ${WP_SRC} ]] && ./download


#======================================================================================================================
# Move WordPress files to /www.
#======================================================================================================================

bcg-echo "Moving WordPress files to ${NGINX_WWW}..."
mv ${WP_SRC}/* ${NGINX_WWW} && rm -rf ${WP_SRC}

[[ -f ${NGINX_WWW}/wp-load.php ]] && bcg-done \
    || bcg-error "WordPress not installed."
