#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# If /wp-content is not empty, delete source wp-content and create link to /wp-content...
#======================================================================================================================

if [ "$(ls -A ${WP_CONTENT})" ] ; then

    bcg-debug "${WP_CONTENT} is not empty."

    bcg-echo "Deleting ${WP_CONTENT_SRC}."
    rm -rf ${WP_CONTENT_SRC}
    bcg-done


#======================================================================================================================
# ...otherwise, move all files and directories in sourc wp-content to /wp-content.
#======================================================================================================================

else

    bcg-echo "Moving ${WP_CONTENT_SRC} files and directories..."
    for CONTENT in ${WP_CONTENT_SRC}/* ; do

        # get file name
        NAME=$(basename -- "${CONTENT}")
        bcg-echo " .. ${NAME}"

        # define new content variable
        IN_WP="${WP_CONTENT}/${NAME}"
        bcg-debug "    moving ${CONTENT} to ${IN_WP}."

        # use slightly different syntax to move files and directories
        if [ -f ${CONTENT} ] ; then
            mv ${CONTENT} ${WP_CONTENT}
        elif [ -d ${CONTENT} ] ; then
            mkdir -p ${IN_WP}
            [[ "$(ls -A ${CONTENT})" ]] && mv ${CONTENT}/* ${IN_WP}/
        fi

    done
    bcg-done

fi


#======================================================================================================================
# Link source wp-content to /wp-content.
#======================================================================================================================

bcg-echo "Linking ${WP_CONTENT_SRC} to ${WP_CONTENT}..."
ln -s ${WP_CONTENT} ${WP_CONTENT_SRC} \
    && chown www:www ${WP_CONTENT_SRC}
bcg-done
