#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Ensure WP_CONTENT exists.
#======================================================================================================================

[[ ! -d ${WP_CONTENT} ]] && mkdir ${WP_CONTENT}


#======================================================================================================================
# Move all files and directories in /www/wp-content to /wp/content.
#======================================================================================================================

bcg-echo "Moving ${NGINX_WWW_WP_CONTENT} files and directories..."
for CONTENT in ${NGINX_WWW_WP_CONTENT}/* ; do

    # get file name
    NAME=$(basename -- "${CONTENT}")
    bcg-echo " .. ${NAME}"

    # if it is already a link, move on
    if [ -L ${CONTENT} ] ; then
        bcg-debug "    already moved."
        continue
    fi

    # define new content variable
    IN_WP="${WP_CONTENT}/${NAME}"

    # if content does not exist in /wp/content, move it from /www/wp-content
    if [ -e ${CONTENT} ] && [ ! -e ${IN_WP} ] ; then
        bcg-debug "    moving ${CONTENT} to ${IN_WP}"

        # use slightly different syntax to move files or directories
        if [ -f ${CONTENT} ] ; then
            mv ${CONTENT} ${IN_WP}
        else
            mkdir -p ${IN_WP}
            if [ "$(ls -A ${CONTENT})" ] ; then
                mv ${CONTENT}/* ${IN_WP}/
            fi
        fi

    else
        bcg-debug "    ${IN_WP} already exists."
    fi

done
bcg-done


#======================================================================================================================
# Move any additional files in /wp/ to /wp/content/ (supports previous versions of the image).
#======================================================================================================================

bcg-echo "Moving any additional content into ${WP_CONTENT}..."
for CONTENT in ${WP_ROOT}/* ; do

    # get file name
    NAME=$(basename -- "${CONTENT}")

    case "${NAME}" in

        content|wp-config.php)
            bcg-debug " .. ignoring ${CONTENT}."
            continue;
            ;;

        *)
            bcg-debug " .. moving ${CONTENT}."
            (cd ${CONTENT} && tar c .) | (cd ${WP_CONTENT} && tar xf -)
            ;;

    esac

done
bcg-done


#======================================================================================================================
# Delete /www/wp-content and link to /wp/content.
#======================================================================================================================

bcg-echo "Removing ${NGINX_WWW_WP_CONTENT} and linking to ${WP_CONTENT}..."
bcg-rmrf "${NGINX_WWW_WP_CONTENT}"
bcg-debug "Creating link to ${WP_CONTENT}."
ln -s ${WP_CONTENT} ${NGINX_WWW_WP_CONTENT}
bcg-done
