#!/bin/bash

set -euo pipefail


#======================================================================================================================
# Set correct permissions on /wp-content.
#======================================================================================================================

bf-echo "Setting permissions on ${WP_CONTENT}..." "wp/set-perms"
bf-ch-apply "${BF_CH_D}/30-wp"
bf-done "wp/set-perms"
