#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If /wp-content already has content in it, delete source wp-content and create link to /wp-content...
#======================================================================================================================

if [ "$(ls -A ${WP_CONTENT})" ] ; then

    bf-debug "${WP_CONTENT} is not empty."

    # if source wp-content is not a link, delete it (it will be recreated as a symlink later)
    if [ ! -L ${WP_CONTENT_SRC} ] ; then

        bf-echo "Deleting ${WP_CONTENT_SRC} so it can be turned into a symlink."
        rm -rf ${WP_CONTENT_SRC}
        bf-done

    fi


#======================================================================================================================
# ...otherwise, move all files and directories in sourc wp-content to /wp-content.
#======================================================================================================================

else

    # /wp-content is empty - if source wp-content is already a link, recreate /wp-content using the default copy
    if [ -L ${WP_CONTENT_SRC} ] ; then

        wp-content-recreate

    # /wp-content is empty - move source wp-content
    else

        bf-echo "Moving ${WP_CONTENT_SRC} files and directories..."
        for CONTENT in ${WP_CONTENT_SRC}/* ; do

            # get file name
            NAME=$(basename -- "${CONTENT}")
            bf-echo " .. ${NAME}"

            # define new content variable
            IN_WP="${WP_CONTENT}/${NAME}"
            bf-debug "    moving ${CONTENT} to ${IN_WP}."

            # move content
            mv ${CONTENT} ${WP_CONTENT}

        done
        bf-done

        wp-content-setperms

    fi

fi


#======================================================================================================================
# Link source wp-content to /wp-content.
#======================================================================================================================

if [ ! -L ${WP_CONTENT_SRC} ] ; then

    bf-echo "Linking ${WP_CONTENT_SRC} to ${WP_CONTENT}..."
    ln -s ${WP_CONTENT} ${WP_CONTENT_SRC} \
        && bf-ch -o www:www ${WP_CONTENT_SRC}
    bf-done

fi
