#!/bin/bash

set -euo pipefail


#======================================================================================================================
# If /wp-content already has content in it, delete source wp-content and create link to /wp-content...
#======================================================================================================================

if [ "$(ls -A ${WP_CONTENT})" ] ; then

    bf-echo "${WP_CONTENT} is not empty - doing nothing." "wp/setup-content"


#======================================================================================================================
# ...otherwise, move all files and directories in sourc wp-content to /wp-content.
#======================================================================================================================

else

    bf-echo "Setting up default wp-content directory." "wp/setup-content"

    # /wp-content is empty - if source wp-content is already a link, recreate /wp-content using the default copy
    if [ -L ${WP_CONTENT_SRC} ] ; then

        wp-content-recreate

    # /wp-content is empty - move source wp-content
    else

        bf-echo "Moving ${WP_CONTENT_SRC} files and directories..." "wp/setup-content"
        for CONTENT in ${WP_CONTENT_SRC}/* ; do

            # get file name
            NAME=$(basename -- "${CONTENT}")
            bf-echo " .. ${NAME}" "wp/setup-content"

            # define new content variable
            IN_WP="${WP_CONTENT}/${NAME}"
            bf-debug "    moving ${CONTENT} to ${IN_WP}." "wp/setup-content"

            # move content
            mv ${CONTENT} ${WP_CONTENT}

        done
        bf-done "wp/setup-content"

        ${WP_LIB}/set-perms

    fi

fi


#======================================================================================================================
# Link source wp-content to /wp-content.
#======================================================================================================================

if [ ! -L ${WP_CONTENT_SRC} ] ; then

    bf-echo "Deleting ${WP_CONTENT_SRC} so it can be turned into a symlink." "wp/setup-content"
    rm -rf ${WP_CONTENT_SRC}

    bf-echo "Linking ${WP_CONTENT_SRC} to ${WP_CONTENT}..." "wp/setup-content"
    ln -s ${WP_CONTENT} ${WP_CONTENT_SRC} \
        && bf-ch -o www:www ${WP_CONTENT_SRC}
    bf-done "wp/setup-content"

fi

${WP_LIB}/set-perms
