#!/usr/bin/with-contenv bash

#======================================================================================================================
# Check for wp-config.php
#======================================================================================================================

if [ -f /www/wp-config.php ] ; then
    echo " - WordPress already installed."
    exit 0
fi


#======================================================================================================================
# Download WordPress
#======================================================================================================================

s6-envuidgid www

cd /tmp

URL="https://en-gb.wordpress.org/wordpress-${WORDPRESS_VERSION}-${WORDPRESS_LOCALE}.zip"
echo " - downloading ${URL}..."
curl -L -o wp.zip ${URL}
tar -xzvf wp.zip && rm wp.zip
echo " - done."

echo " - moving WordPress files to /www..."
rm -rf /www/*
mv wordpress/* /www/ && rm -rf wordpress
echo " - done."
