#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bcg-env "WP_LIB" "${BCG_LIB}/wp"

WP=/wp
bcg-env "WP_ROOT" "${WP}"
bcg-env "WP_CONFIG" "${WP}/wp-config.php"
bcg-env "WP_CONTENT" "${WP}/content"

bcg-env "NGINX_WWW_WP_LOAD" "${NGINX_WWW}/wp-load.php"
bcg-env "NGINX_WWW_WP_CONFIG" "${NGINX_WWW}/wp-config.php"
bcg-env "NGINX_WWW_WP_CONTENT" "${NGINX_WWW}/wp-content"
