#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bcg-env "WP_LIB" "${BCG_LIB}/wp"

bcg-env "WP_CONFIG" "${WP_SRC}/wp-config.php"
bcg-env "WP_CONTENT" "/wp-content"
bcg-env "WP_CONTENT_SRC" "${WP_SRC}/wp-content"
bcg-env "WP_CONTENT_DEFAULT" "${BCG_SRC}/wp-content-default"
