#!/usr/bin/with-contenv bash

#======================================================================================================================
# Check for wp-config.php
#======================================================================================================================

if [ -f /www/wp-config.php ] ; then
    echo " - WordPress already installed."
    exit 0
fi


#======================================================================================================================
# Download WordPress
#======================================================================================================================

function wp () {

    cd /tmp

    URL="https://en-gb.wordpress.org/wordpress-${WORDPRESS_VERSION}-${WORDPRESS_LOCALE}.zip"
    echo " - downloading ${URL}..."
    curl -sL -o wp.zip ${URL}
    tar -xzvf wp.zip && rm wp.zip

    if [ -d ./wordpress ] ; then
        echo " - done."
    else
        echo " - error."
        exit 1
    fi


    #======================================================================================================================
    # Move WordPress files to /www
    #======================================================================================================================

    echo " - moving WordPress files to /www..."
    rm -rf /www/*
    mv wordpress/* /www/ && rm -rf wordpress
    echo " - done."

}

s6-envuidgid www wp
