#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Override configuration
#======================================================================================================================

bcg-echo "Overriding php.ini configuration values..."

declare -A VALUES
VALUES["cgi.fix_pathinfo"]="0"

source /etc/functions/replace.sh
replace VALUES "${PHP_DIR}/php.ini"

bcg-done
