#!/usr/bin/with-contenv bash

set -euo pipefail
source /etc/wp/inc/directories.sh


#======================================================================================================================
# Check for wp-config.php and WORDPRESS_CLEAN_INSTALL
#======================================================================================================================

if [ -L ${WWW}/wp-config.php ] || [ -f ${WWW}/wp-config.php ] ; then

    if [ "${WORDPRESS_CLEAN_INSTALL}" = "1" ] ; then
    
        _echo "Clean install detected, deleting contents of ${WWW}..."
        _rmrf ${WWW}/*
        _done

    else

        _ok "WordPress already installed."
        exit 0

    fi

fi


#======================================================================================================================
# Run installation program
#======================================================================================================================

s6-setuidgid www /etc/wp/install
