#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Override configuration.
#======================================================================================================================

bcg-echo "Overriding php.ini configuration values..."

declare -A VALUES
VALUES["cgi.fix_pathinfo"]="0"

source ${LIB_INC}/php-replace-ini.sh
replace-ini VALUES ${PHP_DIR}/php.ini

bcg-done
