#!/usr/bin/with-contenv bash

source /etc/wp/directories


#======================================================================================================================
# Check for wp-config.php and WORDPRESS_CLEAN_INSTALL
#======================================================================================================================

if [ -L ${WWW}/wp-config.php ] || [ -f ${WWW}/wp-config.php ] ; then
    if [ "${WORDPRESS_CLEAN_INSTALL}" = "0" ] ; then
        echo " - WordPress already installed."
        exit 0
    fi
fi


#======================================================================================================================
# Run installation program
#======================================================================================================================

s6-setuidgid www wp-install
