#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Check for wp-config.php and WP_CLEAN_INSTALL.
#======================================================================================================================

if [ -L ${NGINX_WWW_WP_CONFIG} ] || [ -f ${NGINX_WWW_WP_CONFIG} ] ; then

    if [ "${WP_CLEAN_INSTALL}" = "1" ] ; then

        bcg-echo "Clean install detected."
        bcg-rmrf "${NGINX_WWW}/*"

    else

        bcg-ok "WordPress already installed."
        exit 0

    fi

fi


#======================================================================================================================
# Run installation program.
#======================================================================================================================

s6-setuidgid www ${LIB_WP}/install
