#!/usr/bin/with-contenv bash

set -euo pipefail
source /etc/wp/inc/directories.sh


#======================================================================================================================
# If wp-config.php is a symlink, the setup has already been run
#======================================================================================================================

if [ "${GENERATE_CONFIG}" = "1" ] ; then

    _echo "Generate config detected, removing wp-config.php files..."
    _rmrf ${WWW}/wp-config.php
    _rmrf ${WP}/wp-config.php
    _done

elif [ -L ${WWW}/wp-config.php ] ; then

    _ok "WordPress already configured."
    exit 0

fi


#======================================================================================================================
# Run setup config program
#======================================================================================================================

s6-setuidgid www /etc/wp/setup-config
