#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# If wp-load.php doesn't exist, the source files have not been downloaded correctly.
# If it does, remove source files if WP_CLEAN_INSTALL is set.
#======================================================================================================================

if [ -f ${NGINX_WWW_WP_LOAD} ] ; then

    if [ "${WP_CLEAN_INSTALL}" = "1" ] ; then

        bcg-echo "Clean install detected, removing source files."
        bcg-rmrf "${NGINX_WWW}/*"
        bcg-done

    else

        bcg-ok "WordPress already installed."
        exit 0

    fi

fi


#======================================================================================================================
# Run install executable.
#======================================================================================================================

s6-setuidgid www ${LIB_WP}/install
