#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# If wp-load.php doesn't exist, the source files have not been downloaded correctly.
#======================================================================================================================

[[ ! -f ${NGINX_WWW_WP_LOAD} ]] && bcg-error "WordPress source files have not been installed correctly."


#======================================================================================================================
# If wp-config.php is a symlink, the setup has already been run.
#======================================================================================================================

if [ "${WP_GENERATE_CONFIG}" = "1" ] ; then

    bcg-echo "Generate config detected, removing existing config."
    bcg-rmrf ${NGINX_WWW_WP_CONFIG}
    bcg-rmrf ${WP_CONFIG}
    bcg-done

elif [ -L ${NGINX_WWW_WP_CONFIG} ] ; then

    bcg-ok "WordPress already configured."
    exit 0

fi


#======================================================================================================================
# Run setup config executable.
#======================================================================================================================

s6-setuidgid www ${LIB_WP}/setup-config
