#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# If wp-content doesn't exist, the source files have not been downloaded correctly.
#======================================================================================================================

[[ ! -e ${NGINX_WWW_WP_CONTENT} ]] && bcg-error "WordPress source files do not exist."


#======================================================================================================================
# If wp-content is a symlink, the setup has already been run.
#======================================================================================================================

if [ -L ${NGINX_WWW_WP_CONTENT} ] ; then

    bcg-ok "WordPress content already moved."
    wp-setup-complete
    exit 0

fi


#======================================================================================================================
# Run setup content executable.
#======================================================================================================================

s6-setuidgid www ${LIB_WP}/setup-content
wp-setup-complete
