#!/usr/bin/with-contenv bash

set -euo pipefail

#======================================================================================================================
# Execute WordPress cron
# See https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/
#======================================================================================================================

if [ "${USE_SYSTEM_CRON}" = "1" ] ; then
    _echo "Executing WordPress cron..."
    wget --delete-after http://localhost/wp-cron.php
    _done
fi
