#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Install PHP8 dependencies.
#======================================================================================================================

apk add --no-cache \
    php82-cgi=${1} \
    php82-ctype=${1} \
    php82-curl=${1} \
    php82-dom=${1} \
    php82-exif=${1} \
    php82-fileinfo=${1} \
    php82-ftp=${1} \
    php82-gd=${1} \
    php82-gettext=${1} \
    php82-iconv=${1} \
    php82-imap=${1} \
    php82-intl=${1} \
    php82-mbstring=${1} \
    php82-mysqli=${1} \
    php82-mysqlnd=${1} \
    php82-openssl=${1} \
    php82-simplexml=${1} \
    php82-soap=${1} \
    php82-sockets=${1} \
    php82-sodium=${1} \
    php82-xml=${1} \
    php82-xmlreader=${1} \
    php82-zip=${1}
