#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Install PHP7 dependencies.
#======================================================================================================================

apk fix
apk verify

apk add --no-cache \
    php7-cgi@prevcomm=${1} \
    php7-ctype@prevcomm=${1} \
    php7-curl@prevcomm=${1} \
    php7-dom@prevcomm=${1} \
    php7-exif@prevcomm=${1} \
    php7-fileinfo@prevcomm=${1} \
    php7-ftp@prevcomm=${1} \
    php7-gd@prevcomm=${1} \
    php7-gettext@prevcomm=${1} \
    php7-iconv@prevcomm=${1} \
    php7-imap@prevcomm=${1} \
    php7-intl@prevcomm=${1} \
    php7-json@prevcomm=${1} \
    php7-mbstring@prevcomm=${1} \
    php7-mysqli@prevcomm=${1} \
    php7-mysqlnd@prevcomm=${1} \
    php7-openssl@prevcomm=${1} \
    php7-simplexml@prevcomm=${1} \
    php7-soap@prevcomm=${1} \
    php7-sockets@prevcomm=${1} \
    php7-sodium@prevcomm=${1} \
    php7-xml@prevcomm=${1} \
    php7-xmlrpc@prevcomm=${1} \
    php7-xmlreader@prevcomm=${1} \
    php7-zip@prevcomm=${1}
