#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Install PHP7 dependencies.
#======================================================================================================================

apk add --no-cache \
    php7-cgi=${1} \
    php7-ctype=${1} \
    php7-curl=${1} \
    php7-dom=${1} \
    php7-exif=${1} \
    php7-fileinfo=${1} \
    php7-ftp=${1} \
    php7-gd=${1} \
    php7-gettext=${1} \
    php7-iconv=${1} \
    php7-imap=${1} \
    php8-intl=${1} \
    php7-json=${1} \
    php7-mbstring=${1} \
    php7-mysqlnd=${1} \
    php7-mysqli=${1} \
    php7-sodium=${1} \
    php7-openssl=${1} \
    php7-simplexml=${1} \
    php7-soap=${1} \
    php7-sockets=${1} \
    php7-xml=${1} \
    php7-xmlrpc=${1} \
    php7-xmlreader=${1} \
    php7-zip=${1}
