FROM bcgdesign/wordpress:1.5.0

LABEL maintainer="Ben Green <ben@bcgdesign.com>" \
    org.label-schema.name="WordPress (en_GB)" \
    org.label-schema.version="1.0" \
    org.label-schema.vendor="Ben Green" \
    org.label-schema.schema-version="1.0"

ARG WP_LOCALE="en_GB"
RUN wp-download
