#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Install PHP7 dependencies.
#======================================================================================================================

apk add --no-cache \
    php7-cgi@edgetest=${1} \
    php7-ctype@edgetest=${1} \
    php7-curl@edgetest=${1} \
    php7-dom@edgetest=${1} \
    php7-exif@edgetest=${1} \
    php7-fileinfo@edgetest=${1} \
    php7-ftp@edgetest=${1} \
    php7-gd@edgetest=${1} \
    php7-gettext@edgetest=${1} \
    php7-iconv@edgetest=${1} \
    php7-imap@edgetest=${1} \
    php7-intl@edgetest=${1} \
    php7-json@edgetest=${1} \
    php7-mbstring@edgetest=${1} \
    php7-mysqli@edgetest=${1} \
    php7-mysqlnd@edgetest=${1} \
    php7-openssl@edgetest=${1} \
    php7-simplexml@edgetest=${1} \
    php7-soap@edgetest=${1} \
    php7-sockets@edgetest=${1} \
    php7-sodium@edgetest=${1} \
    php7-xml@edgetest=${1} \
    php7-xmlrpc@edgetest=${1} \
    php7-xmlreader@edgetest=${1} \
    php7-zip@edgetest=${1} \
    icu-data-en-71.1-r2@edgemain
