#!/bin/sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Download WordPress.
#======================================================================================================================

DOWNLOAD=/usr/local/bin/wp-download
chmod +x ${DOWNLOAD} && ${DOWNLOAD} "${WP_VERSION-}" "${WP_LOCALE-}"
