#!/usr/bin/with-contenv bash

set -euo pipefail
source /etc/wp/inc/directories.sh


#======================================================================================================================
# Download WordPress
#======================================================================================================================

cd /tmp

URL="https://${WP_LOCALE}.wordpress.org/latest-${WP_LOCALE}.zip"
bcg-echo "Downloading ${URL}..."
wget -O wp.zip ${URL} \
    && unzip -oq wp.zip \
    && rm wp.zip

if [ -d ./wordpress ] ; then
    bcg-done
else
    bcg-error "WordPress not downloaded."
fi


#======================================================================================================================
# Move WordPress files to /www
#======================================================================================================================

bcg-echo "Moving WordPress files to ${WWW}..."
mv wordpress/* ${WWW} && rm -rf wordpress

if [ -f ${WWW}/wp-load.php ] ; then
    bcg-done
else
    bcg-error "WordPress not installed."
fi
