#!/usr/bin/with-contenv bash

set -euo pipefail
source /etc/wp/inc/directories.sh


#======================================================================================================================
# Download WordPress
#======================================================================================================================

cd /tmp

URL="https://${WORDPRESS_LOCALE}.wordpress.org/latest-${WORDPRESS_LOCALE}.zip"
_echo "Downloading ${URL}..."
wget -O wp.zip ${URL} \
    && unzip -oq wp.zip \
    && rm wp.zip

if [ -d ./wordpress ] ; then
    _done
else
    _error "WordPress not downloaded."
fi


#======================================================================================================================
# Move WordPress files to /www
#======================================================================================================================

_echo "Moving WordPress files to ${WWW}..."
mv wordpress/* ${WWW} && rm -rf wordpress

if [ -f ${WWW}/wp-load.php ] ; then
    _done
else
    _error "WordPress not installed."
fi
