#!/usr/bin/with-contenv bash

set -euo pipefail
source /etc/wp/inc/directories.sh


#======================================================================================================================
# Move each wp-content directory to /wp and create a link
#======================================================================================================================

function move_and_link () {

    # helpful output
    _echo " .. ${1}"

    # define directory variables
    WP_DIR=${WP}/${1}
    WWW_DIR=${WWW_WP_CONTENT}/${1}

    # if dir does not exist in /wp, create it and set ownership
    if [ ! -d ${WP_DIR} ] ; then
        mkdir -p ${WP_DIR} && chown www:www ${WP_DIR}

        # if dir exists in /www/wp-content move contents
        if [ -d ${WWW_DIR} ] ; then
            _echo "    moving contents from ${WWW_DIR} to ${WP_DIR}"
            mv ${WWW_DIR}/* ${WP_DIR}
        fi

    fi

    # check link from /www/wp-content/* directory to /wp/* directory
    if [ ! -L ${WWW_DIR} ] ; then

        # if dir exists in /www/wp-content, delete it
        if [ -d ${WWW_DIR} ] ; then
            _echo "    deleting directory ${WWW_DIR}"
            _rmrf "${WWW_DIR}" > /dev/null 2>&1
        fi

        # create link from /wp to /www/wp-content
        _echo "    creating link from ${WP_DIR} to ${WWW_DIR}"
        ln -s ${WP_DIR} ${WWW_DIR}

    fi

}

_echo "Moving wp-content directories and linking..."
move_and_link "plugins"
move_and_link "themes"
move_and_link "uploads"
_done
