#!/usr/bin/with-contenv bash

set -euo pipefail
source /etc/wp/inc/directories.sh


#======================================================================================================================
# If wp-config.php is a file, move it to /wp - then create a link
#======================================================================================================================

if [ -f ${WWW}/wp-config.php ] ; then
    mv ${WWW}/wp-config.php ${WP}
fi

_echo "Linking wp-config.php..."
ln -s ${WP}/wp-config.php ${WWW}/wp-config.php
_done


#======================================================================================================================
# Move each wp-content directory to /wp and create a link
#======================================================================================================================

function move_and_link () {
    # define directory variables
    WP_DIR=${WP}/${1}
    WP_CONTENT_DIR=${WP_CONTENT}/${1}

    # if dir does not exist in /wp, create it
    if [ ! -d ${WP_DIR} ] ; then
        mkdir -p ${WP_DIR}

        # if dir exists in /www/wp-content move contents
        if [ -d ${WP_CONTENT_DIR} ] ; then
            mv ${WP_CONTENT_DIR}/* ${WP_DIR}
        fi
    fi

    # if dir exists in /www/wp-content, delete it
    if [ -d ${WP_CONTENT_DIR} ] ; then
        _rmrf ${WP_CONTENT_DIR}
    fi

    # create link from /wp to /www/wp-content
    ln -s ${WP_DIR} ${WP_CONTENT_DIR}
}

_echo "Moving wp-content directories and linking..."
move_and_link "plugins"
move_and_link "themes"
move_and_link "uploads"
_done
