name: auto-pr

on:
  create

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    -
      if: github.ref_type == 'branch'
      name: Checkout Branch ${{ github.ref_name }}
      uses: actions/checkout@v3
    -
      name: Create Pull Request
      uses: bfren/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_branch: main
        pr_title: ${{ github.ref_name }}
        pr_body: "Merging branch to create ${{ github.ref_name }}."
