name: publish-php8_1

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-php8_1:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read PHP version - revision
        uses: bfren/read-file@v1
        with:
          file: ./php8.1-edge/overlay/tmp/PHP_REVISION
        id: php_revision
      -
        name: Read WP minor version
        uses: bfren/read-file@v1
        with:
          file: ./overlay/tmp/WP_MINOR
        id: wp_minor
      -
        name: Read WP version
        uses: bfren/read-file@v1
        with:
          file: ./overlay/tmp/WP_VERSION
        id: wp_version
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php8.1-edge/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/wordpress:php8.1
            bfren/wordpress:php8.1-${{ steps.version_major.outputs.contents }}
            bfren/wordpress:php8.1-${{ steps.version_minor.outputs.contents }}
            bfren/wordpress:php8.1-${{ steps.version.outputs.contents }}
            bfren/wordpress:php8.1-wp${{ steps.wp_minor.outputs.contents }}
            bfren/wordpress:php8.1-wp${{ steps.wp_minor.outputs.contents }}-${{ steps.version.outputs.contents }}
            bfren/wordpress:php8.1-wp${{ steps.wp_version.outputs.contents }}
            bfren/wordpress:php8.1-wp${{ steps.wp_version.outputs.contents }}-${{ steps.version.outputs.contents }}
            bfren/wordpress:php${{ steps.php_revision.outputs.contents }}
            ghcr.io/bfren/wordpress:php8.1
            ghcr.io/bfren/wordpress:php8.1-${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/wordpress:php8.1-${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/wordpress:php8.1-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/wordpress:php8.1-wp${{ steps.wp_minor.outputs.contents }}
            ghcr.io/bfren/wordpress:php8.1-wp${{ steps.wp_minor.outputs.contents }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/wordpress:php8.1-wp${{ steps.wp_version.outputs.contents }}
            ghcr.io/bfren/wordpress:php8.1-wp${{ steps.wp_version.outputs.contents }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/wordpress:php${{ steps.php_revision.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
